[package]
name = "copycat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clipboard = "0.5.0"
device_query = "1.1.2"
eframe = "0.21.3"
egui = "0.21.0"
x11-clipboard = "0.7.0"
